services:
  backend_gestor_soporte_uti:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_gestor_soporte_uti
    restart: unless-stopped
    ports:
      - "7001:7001"
    environment:
      NODE_ENV: production
      PORT: 7001
      DATABASE_URL: "postgresql://uti.fce:071.f03@dbpg:5432/ticketuti?schema=public"
    networks:
      - dbpg_dbpg

networks:
  dbpg_dbpg:
    external: true