services:
  backend_gestor_soporte_uti:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bk_sup_uti
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: "7001"
    ports:
      - "7001:7001"
    networks:
      - dbpg_dbpg

networks:
  dbpg_dbpg:
    external: true