services:
  backend_gestor_soporte_uti:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_gestor_soporte_uti
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "7001:7001"
    networks:
      - dbpg_dbpg

networks:
  dbpg_dbpg:
    external: true